;;; dir-treeview-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dir-treeview.el

(autoload 'dir-treeview-open "dir-treeview" "\
Display the directory tree for DIR.
If omitted or nil, read DIR in the minibuffer, with `dir-treeview-default-root'
as preset value.

If there exists a Dir Treeview buffer for the directory DIR, switch to the first
such buffer found in the list of dir Dir Treeview buffers.

If there exists no such buffer, create one and switch to it.

(fn &optional DIR)" t)
(autoload 'dir-treeview "dir-treeview" "\
Display the directory tree for `dir-treeview-default-root'.

If there exists a Dir Treeview buffer for that directory, switch to the first
such buffer found in the list of dir treeview buffers.

If there exists no such buffer, create one and switch to it." t)
(register-definition-prefixes "dir-treeview" '("dir-treeview-"))


;;; Generated autoloads from dir-treeview-pleasant-theme.el

(register-definition-prefixes "dir-treeview-pleasant-theme" '("dir-treeview-pleasant"))

;;; End of scraped data

(provide 'dir-treeview-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dir-treeview-autoloads.el ends here
